version: '2'
services:
    firstjhipster-app:
        image: firstjhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://firstjhipster-mysql:3306/firstjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=firstjhipster-elasticsearch:9300
        ports:
            - 8080:8080
    firstjhipster-mysql:
        extends:
            file: mysql.yml
            service: firstjhipster-mysql
    firstjhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: firstjhipster-elasticsearch
